### ISSUE TITLE
Ditch yarn?

### ISSUE THREAD

**Issue by stevenvachon** [eventualbuddha/keysim.js#53]
npm 5+ has much improved and largely denecessitates yarn

**Comment by eventualbuddha** [comment]
I could be persuaded. Yarn is still the best choice for monorepos, but this isn’t one.

**Comment by stevenvachon** [comment]
* one less [global] dependency
* simpler npm scripts

**Comment by stevenvachon** [comment]
There's also no need for lockfiles in a small public project like this one. They aren't published/used by consumers of the package, so they'll only prevent bugs from being found by the project's devs.

**Comment by eventualbuddha** [comment]
> * one less [global] dependency

The dependency is slightly annoying, but only very slightly. Travis CI has it already, and for local development it's easy to `brew install yarn` or equivalent.

> * simpler npm scripts

I'm not sure how npm simplifies the scripts. You're basically substituting `yarn foo` for `npm run foo`. Same complexity, slightly wordier with npm.

> There's also no need for lockfiles in a small public project like this one.

That I disagree with. I think it's important to keep dependencies locked down and frequently updated with a service like Greenkeeper, and to have some way of being notified that the library doesn't work with the latest in-range version of your dependencies. Greenkeeper can handle that, thought I tend to favor using a Travis CI cron job that runs daily and installs ignoring the lockfile.

Why do I think it's important to lock down dependencies even in libraries? So that PRs don't fail for mysterious reasons.

**Comment by stevenvachon** [comment]
> Why do I think it's important to lock down dependencies even in libraries? So that PRs don't fail for mysterious reasons.

That's better than installations failing after releasing a PR that passed with outdated dependencies.

> Greenkeeper can handle that, thought I tend to favor using a Travis CI cron job that runs daily and installs ignoring the lockfile.

Does this library currently do this?

**Comment by stevenvachon** [comment]
Alright, but I don't see the advantage of using yarn.
